=== testng-team/testng/testng-core/src/main/resources/testng-1.0.dtd
<!--

Here is a quick overview of the main parts of this DTD.  For more information,
refer to the <a href="https://testng.org">main web site</a>.
                                                      
A <b>suite</b> is made of <b>tests</b> and <b>parameters</b>.
                                                      
A <b>test</b> is made of three parts:                        

<ul>
<li> <b>parameters</b>, which override the suite parameters     
<li> <b>groups</b>, made of two parts                           
<li> <b>classes</b>, defining which classes are going to be part
  of this test run                                    
</ul>
                                                      
In turn, <b>groups</b> are made of two parts:                
<ul>
<li> Definitions, which allow you to group groups into   
  bigger groups                                       
<li> Runs, which defines the groups that the methods     
  must belong to in order to be run during this test  
</ul>
                                                      
Cedric Beust & Alexandru Popescu                      
@title DTD for TestNG                                    
@root suite

-->


<!-- A suite is the top-level element of a testng.xml file                  -->
<!ELEMENT suite (groups?,(listeners|packages|test|parameter|method-selectors|suite-files)*) >

<!-- Attributes: -->
<!--
@attr  name        The name of this suite (as it will appear in the reports)
@attr  junit       Whether to run in JUnit mode.
@attr  verbose     How verbose the output on the console will be.  
                This setting has no impact on the HTML reports.
@attr  parallel   Whether TestNG should use different threads
                to run your tests (might speed up the process)
                Do not use "true" and "false" values, they are now deprecated.
@attr  parent-module A module used to create the parent injector of all guice injectors used
       in tests of the suite
@attr  guice-stage The stage with which the parent injector is created
@attr  configfailurepolicy  Whether to continue attempting Before/After
                Class/Methods after they've failed once or just skip remaining.
@attr  thread-count An integer giving the size of the thread pool to use
                if you set parallel.
@attr  annotations  If "javadoc", TestNG will look for
                JavaDoc annotations in your sources, otherwise it will
                use JDK5 annotations.
@attr  time-out     The time to wait in milliseconds before aborting the
                method (if parallel="methods") or the test (parallel="tests")
@attr  skipfailedinvocationcounts Whether to skip failed invocations.
@attr  data-provider-thread-count An integer giving the size of the thread pool to use
       for parallel data providers.
@attr  object-factory A class that implements IObjectFactory that will be used to
       instantiate the test objects.
@attr lazy-factory If true, @Factory produced test class instances are created lazily
      (just-in-time, right before the first configuration/test method of each instance runs)
      instead of eagerly up-front. Honored only for constructor based factories. When unset,
      the TestNG configuration decides (default eager). A @Factory(lazy=...) annotation value
      overrides this suite level attribute.
@attr allow-return-values If true, tests that return a value will be run as well
-->
<!ATTLIST suite
    name CDATA #REQUIRED
    junit (true | false) "false"
    verbose CDATA #IMPLIED
    parallel (false | true | none | methods | tests | classes | instances) "none"
    parent-module CDATA #IMPLIED
    guice-stage (DEVELOPMENT | PRODUCTION | TOOL) "DEVELOPMENT"
    configfailurepolicy (skip | continue) "skip"
    thread-count CDATA "5"
    annotations CDATA #IMPLIED
    time-out CDATA #IMPLIED
    skipfailedinvocationcounts (true | false) "false"
    data-provider-thread-count CDATA "10"
    object-factory CDATA #IMPLIED
    group-by-instances (true | false) "false"
    lazy-factory (true | false) #IMPLIED
    preserve-order (true | false) "true"
    allow-return-values (true | false) "false"
>

<!-- A list of XML files that contain more suite descriptions -->
<!ELEMENT suite-files (suite-file)* >

<!ELEMENT suite-file ANY >
<!ATTLIST suite-file
    path CDATA #REQUIRED
>

<!--
Parameters can be defined at the <suite> or at the <test> level.
Parameters defined at the <test> level override parameters of the same name in <suite>
Parameters are used to link Java method parameters to their actual value, defined here.
-->
<!ELEMENT parameter ANY>
<!ATTLIST parameter
    name CDATA #REQUIRED
    value CDATA #REQUIRED >

<!--
Method selectors define user classes used to select which methods to run.
They need to implement <tt>org.testng.IMethodSelector</tt> 
-->
<!ELEMENT method-selectors (method-selector*) >
<!ELEMENT method-selector ((selector-class)*|script) >
<!ELEMENT selector-class ANY>
<!ATTLIST selector-class
    name CDATA #REQUIRED
  priority CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ATTLIST script
    language CDATA #REQUIRED
>

<!--
A test contains parameters and classes.  Additionally, you can define additional groups ("groups of groups")
-->

<!ELEMENT test (method-selectors?,parameter*,groups?,packages?,classes?) >

<!--
@attr  name         The name of this test (as it will appear in the reports)
@attr  junit        Whether to run in JUnit mode.
@attr  verbose      How verbose the output on the console will be.
                This setting has no impact on the HTML reports.
                Default value: suite level verbose.
@attr  parallel     Whether TestNG should use different threads
                to run your tests (might speed up the process)
                Do not use "true" and "false" values, they are now deprecated.
@attr  thread-count An integer giving the size of the thread pool to be used if
                parallel mode is used. Overrides the suite level value.
@attr  annotations  If "javadoc", TestNG will look for
                JavaDoc annotations in your sources, otherwise it will
                use JDK5 annotations.
@attr  time-out     the time to wait in milliseconds before aborting
                the method (if parallel="methods") or the test (if parallel="tests")
@attr  enabled      flag to enable/disable current test. Default value: true 
@attr  skipfailedinvocationcounts Whether to skip failed invocations.
@attr preserve-order If true, the classes in this tag will be run in the same order as
found in the XML file.
@attr allow-return-values If true, tests that return a value will be run as well
-->
<!ATTLIST test
    name CDATA #REQUIRED 
    junit (true | false) "false"
    verbose  CDATA #IMPLIED
    parallel  (false | true | none | methods | tests | classes | instances) #IMPLIED
    thread-count CDATA #IMPLIED
    annotations  CDATA #IMPLIED
    time-out CDATA #IMPLIED
    enabled (true | false) #IMPLIED
    skipfailedinvocationcounts (true | false) "false"
    preserve-order (true | false) "true"
    group-by-instances (true | false) "false"
    allow-return-values (true | false) "false"
>

<!--
Defines additional groups ("groups of groups") and also which groups to include in this test run
-->
<!ELEMENT groups (define*,run?,dependencies?) >

<!ELEMENT define (include*)>
<!ATTLIST define
    name CDATA #REQUIRED>

<!-- Defines which groups to include in the current group of groups         -->
<!ELEMENT include ANY>
<!ATTLIST include
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    invocation-numbers CDATA #IMPLIED>

<!-- Defines which groups to exclude from the current group of groups       -->
<!ELEMENT exclude ANY>
<!ATTLIST exclude
    name CDATA #REQUIRED>

<!-- The subtag of groups used to define which groups should be run         -->
<!ELEMENT run (include?,exclude?)* >

<!ELEMENT dependencies (group*)>

<!ELEMENT group ANY>
<!ATTLIST group
    name CDATA #REQUIRED
    depends-on CDATA #REQUIRED>

<!-- The list of classes to include in this test                            -->
<!ELEMENT classes (class*,parameter*) >
<!ELEMENT class (methods|parameter)* >
<!ATTLIST class
    name CDATA #REQUIRED >

<!-- The list of packages to include in this test                           -->
<!ELEMENT packages (package*) >
<!-- The package description. 
     If the package name ends with .* then subpackages are included too.
-->
<!ELEMENT package (include?,exclude?)*>
<!ATTLIST package
    name CDATA #REQUIRED >

<!-- The list of methods to include/exclude from this test                 -->
<!ELEMENT methods (include?,exclude?,parameter?)* >

<!-- The list of listeners that will be passed to TestNG -->
<!ELEMENT listeners (listener*) >

<!ELEMENT listener ANY>
<!ATTLIST listener
    class-name CDATA #REQUIRED >

=== testng-team/testng/testng-core/src/test/resources/listeners/github1284/github1284_withlistener.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Github 1284 suite with listener">
    <listeners>
        <listener class-name="org.testng.listeners.samples.github1284.Listener1284" />
    </listeners>

    <test name="Github 1284 Test listener" preserve-order="true">
        <classes>
            <class name="org.testng.listeners.samples.github1284.Sample1284">
                <methods>
                    <include name="testWithListener"/>
                </methods>
            </class>
        </classes>
    </test>
</suite>

=== testng-team/testng/testng-core/src/test/resources/yaml/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="SingleSuite" verbose="2" parallel="false" thread-count="4" configfailurepolicy="continue"
    data-provider-thread-count="3">

  <parameter name="n" value="42" />

  <listeners>
    <listener class-name="test.methodinterceptors.FastTestsFirstInterceptor" />
    <listener class-name="test.invokedmethodlistener.MyListener" />
  </listeners>

  <packages>
    <package name="test.testng355.org.apache.tapestry5">
      <include name="Foo"/>
      <include name="Foo2"/>
      <exclude name="Bar"/>
    </package>
    <package name="test.testng355.org.apache.tapestry5.dom" />
  </packages>

  <test name="Regression2" verbose="2">
    <parameter name="count" value="10"/>
    <groups>
      <run>
        <exclude name="broken" />
      </run>
    </groups>
    <classes>
      <class name="test.listeners.ResultEndMillisTest">
<!-- 
        <methods>
          <include name="withFactory" />
        </methods>
 -->
       </class>
<!-- 
      <class name="test.methodselectors.CommandLineTest">
       <class name="test.inject.NoInjectionTest" />
      <class name="test.tmp.TestFactory" />
      <class name="test.thread.MultiThreadedDependentTest" />
      <class name="test.tmp.B" />
      <class name="test.thread.MultiThreadedDependentTest" />
      <class name="test.thread.FactoryTest" />
      <class name="test.tmp.B" />
      <class name="test.failedreporter.FailedReporterTest" />
        <methods>
          <include name="verifyIPAddress" invocationNumbers="0 2" />
        </methods>
      </class>
 -->
    </classes>
  </test>

</suite>

=== testng-team/testng/testng-core/src/test/resources/testng-single2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Timeout Tests">

  <test name="TimeoutTest" time-out="1000">
      <classes>
          <class name="test.timeout.TestTimeOutSampleTest">
              <methods>
                <include name="timeoutTest"/>
              </methods>
          </class>
      </classes>
  </test>

  <test name="NoTimeoutTest">
      <classes>
          <class name="test.timeout.TestTimeOutSampleTest">
              <methods>
                <include name="timeoutTest"/>
              </methods>
          </class>
      </classes>
  </test>
    
</suite>

=== testng-team/testng/testng-core/src/test/resources/executionlistenersingletoncheck/parent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Parent Suite">
   <listeners>
      <listener class-name="org.testng.listeners.samples.ExecutionListenerAndSuiteListener" />
   </listeners>
   <suite-files>
      <suite-file path="child.xml"/>
   </suite-files> 
   <test name="Parent Test">
        <classes>
            <class name="org.testng.listeners.samples.ExecutionListener1SampleTest"/>
        </classes>
    </test>
</suite>

=== testng-team/testng/testng-core/src/test/resources/yaml/a2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="4" configfailurepolicy="skip" verbose="2" name="SingleSuite" skipfailedinvocationcounts="false" parallel="false" annotations="JDK" data-provider-thread-count="3">
  <parameter name="n" value="42"/>
  <parameter name="p" value="10"/>
  <parameter name="s" value="a b c"/>
  <parameter name="t" value="a,b"/>
  <listeners>
    <listener class-name="test.invokedmethodlistener.MyListener"/>
  </listeners>
  <packages>
    <package name="test.testng355.org.apache.tapestry5">
      <include name="Foo"/>
      <include name="Foo2"/>
      <exclude name="Bar"/>
    </package>
    <package name="test.testng355.org.apache.tapestry5.dom">
    </package>
  </packages>
  <method-selectors>
	  <method-selector>
	    <selector-class name="org.testng.internal.XmlMethodSelector" priority="1"/>
	  </method-selector>
	  <method-selector>
	    <script language="beanshell">
	      <![CDATA[groups.containsKey("test1")]]>
	    </script>
	  </method-selector>
  </method-selectors>
  <test verbose="1" name="Test3" junit="false" preserve-order="false">
    <method-selectors>
      <method-selector>
        <selector-class name="org.testng.internal.XmlMethodSelector" priority="1"/>
      </method-selector>
      <method-selector>
        <script language="beanshell">
          <![CDATA[groups.containsKey("test1")]]>
        </script>
      </method-selector>
    </method-selectors>
    <parameter name="n" value="43"/>
    <parameter name="z" value="foo"/>
    <groups>
      <define name="a">
        <include name="b"/>
        <include name="d"/>
      </define>
      <run>
        <include name="A"/>
        <include name="B"/>
        <exclude name="C"/>
        <exclude name="D"/>
      </run>
    </groups>
    <packages>
      <package name="com.example1">
      </package>
      <package name="com.example2">
      </package>
    </packages>
  </test>
  <test verbose="1" name="Test1" junit="false" preserve-order="false">
    <classes>
      <class name="test.tmp.A">
        <methods>
          <include name="test1"/>
          <include name="test2"/>
          <exclude name="test3"/>
        </methods>
      </class>
      <class name="test.tmp.B"/>
    </classes>
  </test>
  <test verbose="1" name="Test2" junit="false" preserve-order="false">
    <classes>
      <class name="test.tmp.B"/>
    </classes>
  </test>
</suite>

=== testng-team/testng/testng-core/src/test/java/test/groupinvocation/testng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Groups run" verbose="2">
  <test name="External group invocation">
    <groups>
      <run>
        <include name="a"/>
      </run>
    </groups>
    <classes>
      <class name="test.groupinvocation.GroupConfiguration"/>
      <class name="test.groupinvocation.DummyTest"/>
    </classes>
  </test>
  <test name="Failing External BeforeGroups - Group run">
    <groups>
      <run>
        <include name="A"/>
      </run>
    </groups>
    <classes>
      <class name="test.groupinvocation.FailingBeforeGroupMethod"/>
      <class name="test.groupinvocation.DummyTest2"/>
    </classes>
  </test>

  <test name="Failing External BeforeGroups - No group run">
    <classes>
      <class name="test.groupinvocation.FailingBeforeGroupMethod"/>
      <class name="test.groupinvocation.DummyTest2"/>
    </classes>
  </test>
</suite>

=== testng-team/testng/testng-core/src/test/resources/test/methodselectors/sampleTestExclusions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Groups run">
    <test name="External group invocation">
        <groups>
            <run>
                <exclude name="test1" />
            </run>
        </groups>
        <classes>
            <class name="test.methodselectors.SampleTest">
                <methods>
                    <include name="test1" />
                </methods>
            </class>
        </classes>
    </test>
</suite>

=== testng-team/testng/testng-core/src/test/resources/parallel-suites/suite-parallel-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite Parallel 0">

  <suite-files>
    <suite-file path="./suite-parallel-3.xml" />
    <suite-file path="./suite-parallel-2.xml" />
    <suite-file path="./suite-parallel-1.xml" />
  </suite-files>

  <test name="Test0">
    <classes>
      <class name="org.testng.concurrency.samples.Sample2"/>
    </classes>
  </test>
</suite>
